Fix more Unpin issues
Adding "+ Unpin" to the `Archive` struct leads to another error, which is easier to understand:

```
error[E0277]: the trait bound `dyn futures_io::if_std::AsyncRead: std::marker::Unpin` is not satisfied
   --> src/async_tar/archive.rs:101:17
    |
21  | pub struct Archive<R: ?Sized + Read + Unpin> {
    | -------------------------------------------- required by `async_tar::archive::Archive`
...
101 |         let me: &mut Archive<dyn Read> = self;
    |                 ^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Unpin` is not implemented for `dyn futures_io::if_std::AsyncRead`

error[E0277]: the trait bound `dyn futures_io::if_std::AsyncRead: std::marker::Unpin` is not satisfied
   --> src/async_tar/archive.rs:102:12
    |
21  | pub struct Archive<R: ?Sized + Read + Unpin> {
    | -------------------------------------------- required by `async_tar::archive::Archive`
...
102 |         me._unpack(dst.as_ref()).await
    |            ^^^^^^^ the trait `std::marker::Unpin` is not implemented for `dyn futures_io::if_std::AsyncRead`

error[E0277]: the trait bound `dyn futures_io::if_std::AsyncRead: std::marker::Unpin` is not satisfied
   --> src/async_tar/archive.rs:159:28
    |
21  | pub struct Archive<R: ?Sized + Read + Unpin> {
    | -------------------------------------------- required by `async_tar::archive::Archive`
...
159 |         let entries = self._entries()?;
    |                            ^^^^^^^^ the trait `std::marker::Unpin` is not implemented for `dyn futures_io::if_std::AsyncRead`
```

From there, it's catching compiler errors, especially around these things:

```rust
let me: &mut Archive<dyn Read> = self;
```

There's a refactoring for that later, but now, it's "making it work time".

I recommend checking out this commit, as it unlocks a new level of compiler errors!

e Please enter the commit message for your changes. Lines starting